jwt:
  secret: ${JWT_SECRET}
  
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

application:
  title: ClearBalance
  version: 1.0
  
twilio:
  from-number: ${FROM_NUMBER}
  sid-key: ${SID_KEY}
  token-key: ${TOKEN_KEY}
